package com.wokesolutions.ignes.util;

public class Prop {

	public static final String REPORT = "report";
	public static final String USERNAME = "username";
	public static final String TITLE = "title";
	public static final String ADDRESS = "address";
	public static final String GRAVITY = "gravity";
	public static final String LAT = "lat";
	public static final String LNG = "lng";
	public static final String STATUS = "status";
	public static final String CREATIONTIME = "creationtime";
	public static final String EMAIL = "email";
	public static final String LEVEL = "level";
	public static final String POINTS = "points";
	public static final String UPS = "ups";
	public static final String DOWNS = "downs";
	public static final String SPAMS = "spams";
	public static final String NAME = "name";
	public static final String NIF = "nif";
	public static final String LOCALITY = "locality";
	public static final String ISFIRESTATION = "isfirestation";
	public static final String PHONE = "phone";
	public static final String SERVICES = "services";
	public static final String ZIP = "zip";
	public static final String EVENT = "event";
	public static final String COMMENT = "comment";
	public static final String VOTE = "vote";
	public static final String DESCRIPTION = "description";
	public static final String ISPRIVATE = "isprivate";
	public static final String JOB = "job";
	public static final String SKILLS = "skills";
	public static final String GENDER = "gender";
	public static final String BIRTH = "birth";
	public static final String REPORTS = "reports";
	public static final String PROFPIC = "profpic";
	public static final String THUMBNAIL = "thumbnail";
	public static final String TEXT = "text";
	public static final String TASK = "task";
	public static final String WORKER = "worker";
	public static final String INDICATIONS = "indications";
	public static final String TASK_TIME = "tasktime";
	public static final String NOTE = "note";
	public static final String COMMENTS = "comments";
	public static final String CATEGORY = "category";
	public static final String BUDGET = "budget";
	public static final String INFO = "info";
	public static final String APPLICATION_TIME = "applicationtime";
	public static final String WORKERS = "workers";
	public static final String APPLICATIONS = "applications";
}
